<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="belmouden" ignored="0" name="Test" tests="6" failures="2" timestamp="2023-04-18T03:48:34 EDT" time="47.731" errors="0">
  <testcase name="Testcase01_ValidEmail_And_VALIDPassword" time="6.022" classname="Login_TestCases.Login_testcases"/>
  <testcase name="Testcase02_InValidEmail_And_validPassword" time="5.751" classname="Login_TestCases.Login_testcases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Login_TestCases.Login_testcases.Testcase02_InValidEmail_And_validPassword(Login_testcases.java:86)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- Testcase02_InValidEmail_And_validPassword -->
  <testcase name="Testcase03_ValidEmail_And_INvalidPassword" time="5.444" classname="Login_TestCases.Login_testcases"/>
  <testcase name="Testcase04_InValidEmail_And_INvalidPassword2" time="5.642" classname="Login_TestCases.Login_testcases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Login_TestCases.Login_testcases.Testcase04_InValidEmail_And_INvalidPassword2(Login_testcases.java:169)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- Testcase04_InValidEmail_And_INvalidPassword2 -->
  <testcase name="Testcase05_NoEmail_And_NOPassword" time="5.242" classname="Login_TestCases.Login_testcases"/>
  <testcase name="Testcase06_ForgottenButton" time="5.591" classname="Login_TestCases.Login_testcases"/>
</testsuite> <!-- Test -->
