<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="47731" started-at="2023-04-18T03:47:46 EDT" finished-at="2023-04-18T03:48:34 EDT">
    <groups>
    </groups>
    <test name="Test" duration-ms="47731" started-at="2023-04-18T03:47:46 EDT" finished-at="2023-04-18T03:48:34 EDT">
      <class name="Login_TestCases.Login_testcases">
        <test-method status="PASS" signature="setup()[pri:0, instance:Login_TestCases.Login_testcases@7a3d45bd]" name="setup" is-config="true" duration-ms="3441" started-at="2023-04-18T03:47:46 EDT" finished-at="2023-04-18T03:47:49 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="Testcase01_ValidEmail_And_VALIDPassword()[pri:1, instance:Login_TestCases.Login_testcases@7a3d45bd]" name="Testcase01_ValidEmail_And_VALIDPassword" duration-ms="6022" started-at="2023-04-18T03:47:49 EDT" finished-at="2023-04-18T03:47:55 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testcase01_ValidEmail_And_VALIDPassword -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Login_TestCases.Login_testcases@7a3d45bd]" name="tearDown" is-config="true" duration-ms="708" started-at="2023-04-18T03:47:55 EDT" finished-at="2023-04-18T03:47:56 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:Login_TestCases.Login_testcases@7a3d45bd]" name="setup" is-config="true" duration-ms="1305" started-at="2023-04-18T03:47:56 EDT" finished-at="2023-04-18T03:47:57 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="Testcase02_InValidEmail_And_validPassword()[pri:2, instance:Login_TestCases.Login_testcases@7a3d45bd]" name="Testcase02_InValidEmail_And_validPassword" duration-ms="5751" started-at="2023-04-18T03:47:57 EDT" finished-at="2023-04-18T03:48:03 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Login_TestCases.Login_testcases.Testcase02_InValidEmail_And_validPassword(Login_testcases.java:86)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testcase02_InValidEmail_And_validPassword -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Login_TestCases.Login_testcases@7a3d45bd]" name="tearDown" is-config="true" duration-ms="678" started-at="2023-04-18T03:48:03 EDT" finished-at="2023-04-18T03:48:04 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:Login_TestCases.Login_testcases@7a3d45bd]" name="setup" is-config="true" duration-ms="1361" started-at="2023-04-18T03:48:04 EDT" finished-at="2023-04-18T03:48:05 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="Testcase03_ValidEmail_And_INvalidPassword()[pri:3, instance:Login_TestCases.Login_testcases@7a3d45bd]" name="Testcase03_ValidEmail_And_INvalidPassword" duration-ms="5444" started-at="2023-04-18T03:48:05 EDT" finished-at="2023-04-18T03:48:11 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testcase03_ValidEmail_And_INvalidPassword -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Login_TestCases.Login_testcases@7a3d45bd]" name="tearDown" is-config="true" duration-ms="652" started-at="2023-04-18T03:48:11 EDT" finished-at="2023-04-18T03:48:11 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:Login_TestCases.Login_testcases@7a3d45bd]" name="setup" is-config="true" duration-ms="1203" started-at="2023-04-18T03:48:11 EDT" finished-at="2023-04-18T03:48:13 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="Testcase04_InValidEmail_And_INvalidPassword2()[pri:4, instance:Login_TestCases.Login_testcases@7a3d45bd]" name="Testcase04_InValidEmail_And_INvalidPassword2" duration-ms="5642" started-at="2023-04-18T03:48:13 EDT" finished-at="2023-04-18T03:48:18 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Login_TestCases.Login_testcases.Testcase04_InValidEmail_And_INvalidPassword2(Login_testcases.java:169)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testcase04_InValidEmail_And_INvalidPassword2 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Login_TestCases.Login_testcases@7a3d45bd]" name="tearDown" is-config="true" duration-ms="692" started-at="2023-04-18T03:48:18 EDT" finished-at="2023-04-18T03:48:19 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:Login_TestCases.Login_testcases@7a3d45bd]" name="setup" is-config="true" duration-ms="1315" started-at="2023-04-18T03:48:19 EDT" finished-at="2023-04-18T03:48:20 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="Testcase05_NoEmail_And_NOPassword()[pri:5, instance:Login_TestCases.Login_testcases@7a3d45bd]" name="Testcase05_NoEmail_And_NOPassword" duration-ms="5242" started-at="2023-04-18T03:48:20 EDT" finished-at="2023-04-18T03:48:25 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testcase05_NoEmail_And_NOPassword -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Login_TestCases.Login_testcases@7a3d45bd]" name="tearDown" is-config="true" duration-ms="626" started-at="2023-04-18T03:48:25 EDT" finished-at="2023-04-18T03:48:26 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:Login_TestCases.Login_testcases@7a3d45bd]" name="setup" is-config="true" duration-ms="1381" started-at="2023-04-18T03:48:26 EDT" finished-at="2023-04-18T03:48:27 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="Testcase06_ForgottenButton()[pri:6, instance:Login_TestCases.Login_testcases@7a3d45bd]" name="Testcase06_ForgottenButton" duration-ms="5591" started-at="2023-04-18T03:48:27 EDT" finished-at="2023-04-18T03:48:33 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testcase06_ForgottenButton -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Login_TestCases.Login_testcases@7a3d45bd]" name="tearDown" is-config="true" duration-ms="638" started-at="2023-04-18T03:48:33 EDT" finished-at="2023-04-18T03:48:34 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Login_TestCases.Login_testcases -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
